### ISSUE TITLE
Slideshow does not advance at the beginning even after interval time has elapsed

### ISSUE THREAD

**Issue by BackwardJet** [tejvuligonda/Web-Slideshow#7]
It could just be loading the JS and CSS files?

**Comment by tejvuligonda** [comment]
See: https://www.w3schools.com/bootstrap/bootstrap_ref_js_carousel.asp under "Carousel Options" with the option "hover". I believe this could be a user error caused by inadvertent hovering.

**Comment by tejvuligonda** [comment]
After setting pause to false, the bug does not happen anymore. Thus, I am closing the issue.
